TpDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rentals.urls')),
    path('admin/', admin.site.urls),
]

rentals/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'rentals'
urlpatterns = [
    path('', views.estate_filter, name='filter'),
    path('make_filter/', views.make_filter, name='makefilter'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('<int:estate_id>/', views.details, name='details'),
    path('<int:estate_id>/reserve/', views.reserve, name='reserve'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentals/models.py
from django.db import models


class Facility(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Facility'
        verbose_name_plural = 'Facilities'

    def __str__(self):
        return self.name


class NameField(models.CharField):  # pasa la variable a lowercase
    def __init__(self, *args, **kwargs):
        super(NameField, self).__init__(*args, **kwargs)

    def get_prep_value(self, value):
        return str(value).lower()


class City(models.Model):
    name = NameField(max_length=50)

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Estate(models.Model):
    title = models.CharField(max_length=30)
    zone = models.CharField(max_length=20)
    description = models.TextField(max_length=500)
    pax = models.IntegerField()
    amount = models.FloatField()
    commission = models.FloatField(default='0.08', editable=False)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    facility = models.ManyToManyField(Facility)
    image = models.ImageField(upload_to='estate_images')

    def __str__(self):
        return self.title


class Reservation(models.Model):
    estate = models.ForeignKey(Estate, on_delete=models.CASCADE)
    date = models.DateField()
    code = models.CharField(max_length=100, editable=False)
    amount = models.FloatField(editable=False, default=0)
    guest_name = models.CharField(max_length=50, blank=True, null=False, editable=False)
    guest_last_name = models.CharField(max_length=50, blank=True, editable=False)
    guest_email = models.EmailField(blank=True, editable=False)

    def __str__(self):
        return "Reservation: " + self.estate.__str__()


class RentalDate(models.Model):
    estate = models.ForeignKey(Estate, on_delete=models.CASCADE)
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField()

    def __str__(self):
        return self.estate.__str__() + " " + self.date.__str__()

rentals/views.py
import datetime
import uuid

from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from rentals.models import Estate, Reservation, RentalDate, City

date_list = []
estates = []


class HomeView(generic.ListView):
    template_name = 'rentals/home.html'
    context_object_name = 'estates_list'

    def get_queryset(self):
        return estates


def estate_filter(request):
    today = datetime.date.today()
    today_date = datetime.datetime.strptime(today.__str__(), "%Y-%m-%d").__str__()
    return render(request, 'rentals/filter.html', {"today_date": today_date})


def make_filter(request):
    # limpiamos las variables globales
    global estates
    global date_list
    if len(estates) != 0:
        estates = []
    if len(date_list) != 0:
        date_list = []

    if request.method == 'POST':
        since_date = request.POST['since_date']
        to_date = request.POST['to_date']
        since_date = datetime.datetime.strptime(since_date, "%Y-%m-%d").date()
        to_date = datetime.datetime.strptime(to_date, "%Y-%m-%d").date()
        date_is_valid = check_date(since_date, to_date)
        if date_is_valid:
            city = request.POST['city']
            city = city.lower()
            total_pax = request.POST['pax']
            # creamos un array de fechas con los dias requeridos
            while since_date != to_date:
                date_list.append(since_date)
                since_date = since_date + datetime.timedelta(days=1)
            date_list.append(to_date)

            try:
                city = City.objects.get(name=city)
                estates_c = Estate.objects.filter(city=city, pax__gte=total_pax)  # filtro por ciudad y por pax

                for estate in estates_c:  # recorro todas las propiedades que cumplen con la cuidad y el pax
                    flag = 0
                    for date in date_list:  # para cada propiedad me traigo el rental_date correspondiente a esa fecha
                        rentals_date = RentalDate.objects.filter(estate_id=estate.id, date=date, reservation=None)
                        if not rentals_date:  # si rentals_date viene vacio, la propiedad no tiene ese dia para reservar
                            flag = 1
                    if flag == 0:  # si el flag es 0 significa que cumple con todas las fechas
                        estates.append(estate)
                return HttpResponseRedirect(reverse('rentals:home'))
            except City.DoesNotExist:
                return HttpResponseRedirect(reverse('rentals:home'))
        else:
            return render(request, 'rentals/filter.html', {"flag": True})


def check_date(since_date, to_date):
    if since_date > to_date:
        return False
    return True


def details(request, estate_id):
    try:
        estate = Estate.objects.get(pk=estate_id)
        subtotal = estate.amount * len(date_list)
        commission = estate.commission * estate.amount
        total = subtotal + subtotal * estate.commission
        total = round(total, 2)
        subtotal = round(subtotal, 2)
        commission = round(commission, 2)
       
        context = {
            'estate': estate,
            'since_date': date_list[0],
            'to_date': date_list[-1],
            'subtotal': subtotal,
            'commission': commission,
            'total': total,
        }
    except Estate.DoesNotExist:
        pass
    return render(request, 'rentals/details.html', context)


def reserve(request, estate_id):
    try:
        global estates
        estate = get_object_or_404(Estate, pk=estate_id)
        date = datetime.date.today().__str__()
        code = uuid.uuid4().__str__()
        if request.method == 'POST':
            guest_name = request.POST['name']
            guest_last_name = request.POST['last_name']
            guest_email = request.POST['email']
            reservation = Reservation(estate=estate, date=date, code=code, guest_name=guest_name,
                                      guest_last_name=guest_last_name, guest_email=guest_email)
            reservation.save()

            for date in date_list:
                rental_date = RentalDate.objects.filter(date=date, estate=estate_id)
                rental_date = rental_date[0]
                rental_date.reservation = reservation
                rental_date.save()

            estates.remove(estate)
            amount = reservation.estate.amount * reservation.estate.rentaldate_set.filter(
                reservation=reservation).count()
            reservation.amount = amount + amount * estate.commission
            reservation.save()

            reserve_done = True
            context = {
                'reserve_done': reserve_done,
                'estates_list': estates,
            }

            return render(request, 'rentals/home.html', context)
    except Estate.DoesNotExist:
        raise Http404("Ups! There was a problem!")

rentals/templates/rentals/base.html
<html>

<head>

  {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'rentals/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     <script src="https://kit.fontawesome.com/a820c1f4b4.js" crossorigin="anonymous"></script>
     <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"> -->

    <!-- Styles
    <link href="{% static 'rentals/css/gestion.css' %}" rel="stylesheet">  -->
    
    <style>
      body {
  font-family: 'Lora';
  /*background: linear-gradient(rgba(47, 23, 15, 0.65), rgba(47, 23, 15, 0.65)), url("../img/bg_main.jpg");*/
  background-color: #222;
  background-attachment: fixed;
  background-position: center;
  background-size: cover;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: 'Raleway';
}

p {
  line-height: 1.75;
}

.text-faded {
  color: rgba(255, 255, 255, 0.3);
}

.site-heading {
  margin-top: 5rem;
  margin-bottom: 5rem;
  text-transform: uppercase;
  line-height: 1;
  font-family: 'Raleway';
}

.site-heading .site-heading-upper {
  display: block;
  font-size: 2rem;
  font-weight: 800;
}

.site-heading .site-heading-lower {
  font-size: 5rem;
  font-weight: 100;
  line-height: 4rem;
}

.page-section {
  margin-top: 5rem;
  margin-bottom: 5rem;
}

.section-heading {
  text-transform: uppercase;
}

.section-heading .section-heading-upper {
  display: block;
  font-size: 1rem;
  font-weight: 800;
  padding-bottom:.5rem;

}

.section-heading .section-heading-lower {
  display: block;
  font-size: 3rem;
  font-weight: 100;
}


.section-heading .section-heading-under {
  display: block;
  font-size: 1rem;
  text-transform: none;
  font-weight: 300;
  margin-top:.5rem;
}

.bg-faded {
  background-color: rgba(255, 255, 255, 0.85);
}

#mainNav {
  background-image: linear-gradient(45deg, #0f9124,rgba(24, 64, 8, 0.8));
  font-family: 'Raleway';
}

#mainNav .navbar-brand {
  color: #ffffff;
}

#mainNav .navbar-nav .nav-item .nav-link {
  color: rgba(255, 255, 255, 0.7);
  font-weight: 800;
}

#mainNav .navbar-nav .nav-item.active .nav-link {
  color: #ffffff;
  text-decoration: underline;
}

@media (min-width: 992px) {
  #mainNav .navbar-nav .nav-item .nav-link {
    font-size: 0.9rem;
  }
  #mainNav .navbar-nav .nav-item .nav-link:hover {
    color: rgba(255, 255, 255, 0.4);
    text-decoration: underline;
  }
  #mainNav .navbar-nav .nav-item.active .nav-link:hover {
    color: #ffffff;
    text-decoration: underline;
  }
}

.btn-xl {
  font-weight: 700;
  font-size: 0.8rem;
  padding-top: 1.5rem;
  padding-bottom: 1.5rem;
  padding-left: 2rem;
  padding-right: 2rem;
}

.intro {
  position: relative;
}

@media (min-width: 992px) {
  .intro .intro-img {
    width: 75%;
    float: left;
  }
  .intro .intro-text {
    left: 600;
    width: 60%;
    margin-top: 3rem;
    background-color: rgba(24, 64, 8);
    color: cornsilk;
    position: absolute;
  }
  .intro .intro-text .intro-button {
    width: 100%;
    left: 0;
    position: absolute;
    bottom: -2rem;
  }
}

@media (min-width: 1200px) {
  .intro .intro-text {
    width: 45%;
  }
}

.cta {
  padding-top: 5rem;
  padding-bottom: 5rem;
  background-color: rgb(242, 245, 240);
}

.cta .cta-inner {
  position: relative;
  padding: 3rem;
  margin: 0.5rem;
  background-color: rgba(24, 64, 8);
  color: cornsilk;
}

.cta .cta-inner:before {
  border-radius: 0.5rem;
  content: '';
  position: absolute;
  top: -0.5rem;
  bottom: -0.5rem;
  left: -0.5rem;
  right: -0.5rem;
  border: 0.25rem solid rgba(255, 255, 255, 0.85);
}

.cta .cta-innerv {
  position: relative;
  padding: 3rem;
  margin: 0.5rem;
  background-color: rgba(255, 255, 255, 0.85);
}

@media (min-width: 992px) {
  .about-heading .about-heading-img {
    position: relative;
    z-index: 0;
  }
  .about-heading .about-heading-content {
    margin-top: -5rem;
    position: relative;
    z-index: 1;
  }
}

@media (min-width: 992px) {
  .product-item .product-item-title {
    position: relative;
    z-index: 1;
    margin-bottom: -3rem;
  }
  .product-item .product-item-img {
    position: relative;
    z-index: 0;
    max-width: 60vw;
  }
  .product-item .product-item-description {
    position: relative;
    z-index: 1;
    margin-top: -3rem;
    max-width: 50vw;
  }
}



@media (min-width: 992px) {
  .list-hours {
    width: 50%;
    font-size: 1.1rem;
  }
}

.address strong {
  font-size: 1.2rem;
}

.footer {
  background-image: linear-gradient(45deg, #0f9124, rgba(24, 64, 8, 0.8));
  
}



.btn {
  box-shadow: 0px 3px 3px 0px rgba(33, 37, 41, 0.1);
}



.font-weight-light {
  font-weight: 100 !important;
}

.mbtm{
  padding-top: 5rem;
}

.mbt{
  padding-top: 2rem;
}

.mbt1{
  padding-top: 1.25rem;
}

a.link{
  color: rgba(255, 255, 255, 0.7);
}

a.link:hover{
  text-decoration: none;
  color: rgba(255, 255, 255, 0.4);
}

.section-content{
  font-family: 'Lora' !important;
  font-size: 16px !important;
  font-weight: 400 !important;
  line-height: 28px !important;
}

ul.errorlist{
  padding-top: .75rem;
  font-style: italic;
  color: red;
}

.bd-placeholder-img {
  font-size: 1.125rem;
  text-anchor: middle;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

@media (min-width: 768px) {
  .bd-placeholder-img-lg {
  font-size: 3.5rem;
  }
}
.myCard .butt{
  background: linear-gradient(45deg, #28ad33, #1a6b20);
  color: #fff;
  width: 230px;
  border: none;
  border-radius: 25px;
  padding: 10px;
  -webkit-box-shadow: 0px 10px 41px -11px rgba(0,0,0,0.7);
  -moz-box-shadow: 0px 10px 41px -11px rgba(0,0,0,0.7);
  box-shadow: 0px 10px 41px -11px rgba(0 ,0 ,0 ,0.7);
}
.myCard .butt:hover{
  background: linear-gradient(45deg, #007bff, #2ab835);
}
.myCard .butt:focus{
  outline: none;
}
.myCard .fas{
  position: relative;
  color: seagreen;
}
.myCard{
  position: relative;
  background: #fff;
  border-radius: 15px;
  -webkit-box-shadow: 0px 10px 40px -10px rgba(0 ,0 ,0 ,0.7);
  -moz-box-shadow: 0px 10px 40px -10px rgba(0 ,0 ,0 ,0.7);
  box-shadow: 0px 10px 40px -10px rgba(0 ,0 ,0 ,0.7);
} 
    </style>
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Propiedades</span>
      </h1>

 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'rentals:home' %}">Inicio</a>
          </li>
          <li class="nav-item active px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'rentals:filter' %}">Filtrar</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<!-- Content that is going to change -->
{% block content %} {% endblock %}


     <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        
	        <a href="https://github.com/FedeAlesandro/UTN-Django-Metodologia" target="_blank" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-github fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	       
	    </p>
        <p class="m-0 mbt1">&copy; TP <a style="color: rgba(255, 255, 255, 0.3);" target="_blank" href="https://www.djangoproject.com/">DJANGO</a> 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'rentals/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'rentals/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

rentals/templates/rentals/details.html
<!-- Content that is going to chance -->
{% extends "rentals/base.html" %}
<!-- this is really important is telling the template that is going to load the extend -->
{% load static %}

<!-- Content that is going to change -->
{%  block content %}
<div style="background-color: azure;">
  <div class="container dark-grey-text">
    <div class="row">
      <div class="col-lg" style="margin-top: 20px; margin-bottom:20px">
        <p class="h2">{{estate.title}}</p>
        <small class="text-muted text-right">Zona <cite title="zone">{{estate.zone}}</cite></small>
        <hr>
        <img src="{{ estate.image.url }}" style="height: 450px; width: 700px; border-radius: 10px;" class="myCard img-fluid" alt="Estate image">
        <hr>
      </div>
      <div class="col-sm-4" style="margin-top: 100px; margin-bottom:20px;">
        <div class="card " style="width: 20rem; margin-left: 30px;">
          <div class="myCard card-body text-center">
            <h5 class="card-title">Haz la reserva!</h5>
            <hr>
            <ul class="list-group">
              <li style="background: linear-gradient(45deg, #007bff, #1a6b20); color: white;" class="list-group-item">Datos de la reserva</li>
              <li class="list-group-item py-2"><i class="fas fa-calendar"></i> Desde: {{since_date}}</li>
              <li class="list-group-item py-2"><i class="fas fa-calendar"></i> Hasta: {{to_date}}</li>
              <li class="list-group-item py-2"> <i class="fas fa-users"></i> Personas: {{estate.pax}}</li>
              <li class="list-group-item py-2">Subtotal: <i class="fas fa-dollar-sign"></i> {{subtotal}}</li>
              <li class="list-group-item py-2">Comisión: <i class="fas fa-dollar-sign"></i> {{commission}}</li>
              <li class="list-group-item py-2 font-weight-bold">Total: <i class="fas fa-dollar-sign"></i> {{total}}</li>

            </ul>
            <hr>
            <button type="button" class="butt btn btn-primary" data-toggle="modal" data-target="#reserve">
              Reservar
            </button>
          </div>
        </div>
      </div>
    </div>
    <div style="margin-bottom: 30px;" class="row">
          <div class="col-4">
            <div class="list-group" id="list-tab" role="tablist">
              <a  class="list-group-item list-group-item-action active" id="list-description-list" data-toggle="list"
                href="#list-description" role="tab" aria-controls="description">Descripción</a>
              <a class="list-group-item list-group-item-action" id="list-facilities-list" data-toggle="list"
                href="#list-facilities" role="tab" aria-controls="facilities">Servicios</a>
            </div>
          </div>
          <div class="col-8">
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="list-description" role="tabpanel"
                aria-labelledby="list-description-list">
                <blockquote class="list-group">
                  <p class="list-group-item text-justify text-break" style="text-indent: 10px; word-wrap:break-word;">{{estate.description}}</p>
                </blockquote>
              </div>
              <div class="tab-pane fade" id="list-facilities" role="tabpanel" aria-labelledby="list-facilities-list">
                <ul class="list-group">
                  {% for facility in estate.facility.all %}
                  <li class="list-group-item py-2">{{facility}}</li>
                  {% endfor %}
                </ul>
              </div>
              <br>
            </div>
          </div>
        </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="reserve" tabindex="-1" role="dialog" aria-labelledby="reserveLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form action="{% url 'rentals:reserve' estate.id %}" method="POST">
          {% csrf_token %}
          <div class="modal-header" style="background: linear-gradient(45deg, #007bff, #1a6b20); color: white;">
            <h5 class="modal-title" id="exampleModalLabel">Reservar</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: honeydew;">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <!-- contact form -->
            <div class="row">
              <!-- Name -->
              <div class="col-sm-12">
                <div class="form-group">
                  <label class="control-label" for="name">Nombre</label>
                  <input class="form-control" id="name" type="text" name="name" required
                    data-error="Please enter your name">
                  <div class="help-block with-errors"></div>
                </div>
              </div>
              <!-- Last name -->
              <div class="col-sm-12">
                <div class="form-group">
                  <label class="control-label" for="last_name">Apellido</label>
                  <input class="form-control" id="last_name" type="text" name="last_name" required
                    data-error="Please enter your last name">
                  <div class="help-block with-errors"></div>
                </div>
              </div>
              <!-- Email -->
              <div class="col-sm-12">
                <div class="form-group">
                  <label class="control-label" for="email">Email</label>
                  <input class="form-control" id="email" type="email" name="email" required
                    data-error="Please enter your Email">
                  <div class="help-block with-errors"></div>
                </div>
              </div>
            </div>
            <div class="modal-footer" >
              <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
              <button class="btn btn-success" type="submit">Confirmar</button>
            </div>
        </form>
      </div>
    </div>
  </div>

</div>
{% endblock %}

rentals/templates/rentals/home.html
<!-- Content that is going to chance -->
{% extends "rentals/base.html" %}
<!-- this is really important is telling the template that is going to load the extend -->
{% load static %}

<!-- Content that is going to change -->
{%  block content %}
<div style="background-color: azure;">
  <div class="container">
    {% if reserve_done %}
      <br>
      <div class="text-center alert alert-primary alert-dismissible fade show col-6" style="margin: auto" alert">
        <h4 class="alert-heading" style="font-weight: 600;">Reserva realizada con exito!</h4>
            <hr>
        <p style="font-family: sans-serif;" class="mb-0"> Verá la información de la reserva en su casilla de mail.</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endif %}

    <!--Section: Offers-->
    <section style="background-color: azure;" id="offers" class="pt-2 pb-3">

      <!-- Grid row -->
      <div class="row mt-4">
        {% if estates_list %}
        {% for estate in estates_list %}
        <!-- Grid column -->
        <div class="cardCont col-md-6 col-lg-4">

          <!--Card-->
          <div class="myCard card card-personal mb-4">

            <!--Card image-->
            <div class="view overlay">
              <a href="{% url 'rentals:details' estate.id %}">
                <img style="height: 260px;" class="card-img-top" src="{{ estate.image.url }}" alt="Estate picture">
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body">
              <!--Title-->
              <a>
                <h5 class="font-weight-bold text-uppercase">
                  {{estate.title}}
                </h5>
              </a>
              <a>
                <span class="badge badge-success py-2 px-2">${{estate.amount}}</span>
              </a>

              <!--Text-->
              <p class="grey-text mt-2">Zona: {{estate.zone}}
                <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div style="left: 100;" class="col-lg-4 col-md-12 text-center">
                  <p class="dark-grey-text">
                    <i class="fas fa-hotel dark-grey-text" aria-hidden="true"></i> {{estate.pax}} Pers</p>
                </div>
                <!--Grid column-->



              </div>
              <!--Grid row-->
              </p>
              <hr>
              <!--Grid column-->
              <div class="col-12 text-center">
                <a href="{% url 'rentals:details' estate.id %}"
                  class="butt btn btn-success btn-sm font-weight-bold btn-rounded">
                  Seleccionar
                </a>
              </div>
              <!--Grid column-->

            </div>
            <!--Card content-->

          </div>
          <!--Card-->
        </div>
        {% endfor %}
        {% else %}
        <h3 class="alert alert-info" role="alert" style="text-align: center; margin-left: 170px;">
          <strong style="text-align: center;">No hay propiedades para mostrar con los datos ingresados</strong>
        </h3>

        {% endif %}
        <!-- Grid row -->
      </div>

    </section>
    <!--Section: Offers-->
  </div>
</div>
{% endblock %}